CRB-142: Add CI job to build container and verify healtcheck
gluwa/creditcoin-legacy pull request #40
Opened 2021-07-28 09:53 UTC by atodorov

2021-08-03 23:29 UTC, seandeneen-gluwa commented on .github/workflows/container.yml
> +    - name: Verify healtcheck
Minor typo here.

2021-08-03 23:55 UTC, will-gluwa commented on .github/workflows/container.yml
> +    - name: Verify healtcheck
```suggestion
    - name: Verify healthcheck
```

2021-08-04 18:49 UTC, seandeneen-gluwa requested changes

2021-08-04 18:49 UTC, seandeneen-gluwa commented on .github/workflows/container.yml
> +        docker inspect -f '{{.State.Health.Status}}' container-under-test
One of the checks are failing with the following message:

`Template parsing error: template: :1:8: executing "" at <.State.Health.Status>: map has no entry for key "Health"`

Is this expected?

2021-08-04 19:12 UTC, atodorov commented on .github/workflows/container.yml
> +        docker inspect -f '{{.State.Health.Status}}' container-under-test
yes, b/c the container doesn't provide a command for a health check. IDK what that command should be but I'm happy to implement it if somebody can decide on it.

2022-04-01 19:05 UTC, closed without merging